package at.owlsoft.owl.corbamodel.user;


/**
* at/owlsoft/owl/corbamodel/user/_SystemUserStatusEntryListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public final class _SystemUserStatusEntryListHolder implements org.omg.CORBA.portable.Streamable
{
  public at.owlsoft.owl.corbamodel.user.ICorbaSystemUserStatusEntry value[] = null;

  public _SystemUserStatusEntryListHolder ()
  {
  }

  public _SystemUserStatusEntryListHolder (at.owlsoft.owl.corbamodel.user.ICorbaSystemUserStatusEntry[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = at.owlsoft.owl.corbamodel.user._SystemUserStatusEntryListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    at.owlsoft.owl.corbamodel.user._SystemUserStatusEntryListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return at.owlsoft.owl.corbamodel.user._SystemUserStatusEntryListHelper.type ();
  }

}
