package at.owlsoft.owl.corbamodel.user;


/**
* at/owlsoft/owl/corbamodel/user/CorbaSystemUserStatus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public class CorbaSystemUserStatus implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static at.owlsoft.owl.corbamodel.user.CorbaSystemUserStatus[] __array = new at.owlsoft.owl.corbamodel.user.CorbaSystemUserStatus [__size];

  public static final int _Active = 0;
  public static final at.owlsoft.owl.corbamodel.user.CorbaSystemUserStatus Active = new at.owlsoft.owl.corbamodel.user.CorbaSystemUserStatus(_Active);
  public static final int _InactiveBecauseOverdue = 1;
  public static final at.owlsoft.owl.corbamodel.user.CorbaSystemUserStatus InactiveBecauseOverdue = new at.owlsoft.owl.corbamodel.user.CorbaSystemUserStatus(_InactiveBecauseOverdue);
  public static final int _InactiveBecauseMembershipFee = 2;
  public static final at.owlsoft.owl.corbamodel.user.CorbaSystemUserStatus InactiveBecauseMembershipFee = new at.owlsoft.owl.corbamodel.user.CorbaSystemUserStatus(_InactiveBecauseMembershipFee);

  public int value ()
  {
    return __value;
  }

  public static at.owlsoft.owl.corbamodel.user.CorbaSystemUserStatus from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected CorbaSystemUserStatus (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class CorbaSystemUserStatus
