package at.owlsoft.owl.corbamodel.user;


/**
* at/owlsoft/owl/corbamodel/user/ICorbaSystemUserStatusEntryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public interface ICorbaSystemUserStatusEntryOperations 
{
  long getDate ();
  String getComment ();
  at.owlsoft.owl.corbamodel.user.CorbaSystemUserStatus getSystemUserStatus ();
  at.owlsoft.owl.corbamodel.user.ICorbaSystemUser getSystemUser ();
} // interface ICorbaSystemUserStatusEntryOperations
