package at.owlsoft.owl.corbamodel.user;


/**
* at/owlsoft/owl/corbamodel/user/ICorbaSystemUserOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public interface ICorbaSystemUserOperations 
{
  int getUserID ();
  int getCardID ();
  String getUsername ();
  String getPassword ();
  String getEmail ();
  String getFirstName ();
  String getLastName ();
  long getBirthday ();
  int getActivityCount ();
  at.owlsoft.owl.corbamodel.accounting.ICorbaActivity[] getActivities ();
  at.owlsoft.owl.corbamodel.user.ICorbaRole[] getRoles ();
  at.owlsoft.owl.corbamodel.user.ICorbaSystemUserTransaction[] getSystemUserTransactions ();
  at.owlsoft.owl.corbamodel.user.ICorbaSystemUserStatusEntry[] getSystemUserStatusEntries ();
  at.owlsoft.owl.corbamodel.user.CorbaSystemUserStatus getCurrentStatus ();
} // interface ICorbaSystemUserOperations
