package at.owlsoft.owl.corbamodel.user;


/**
* at/owlsoft/owl/corbamodel/user/TransactionType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public class TransactionType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static at.owlsoft.owl.corbamodel.user.TransactionType[] __array = new at.owlsoft.owl.corbamodel.user.TransactionType [__size];

  public static final int _MemberFee = 0;
  public static final at.owlsoft.owl.corbamodel.user.TransactionType MemberFee = new at.owlsoft.owl.corbamodel.user.TransactionType(_MemberFee);
  public static final int _OverdueFee = 1;
  public static final at.owlsoft.owl.corbamodel.user.TransactionType OverdueFee = new at.owlsoft.owl.corbamodel.user.TransactionType(_OverdueFee);
  public static final int _Donation = 2;
  public static final at.owlsoft.owl.corbamodel.user.TransactionType Donation = new at.owlsoft.owl.corbamodel.user.TransactionType(_Donation);

  public int value ()
  {
    return __value;
  }

  public static at.owlsoft.owl.corbamodel.user.TransactionType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected TransactionType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class TransactionType
