package at.owlsoft.owl.corbamodel;


/**
* at/owlsoft/owl/corbamodel/ISearchFieldDefinition.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public interface ISearchFieldDefinition extends ISearchFieldDefinitionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ISearchFieldDefinition
