package at.owlsoft.owl.corbamodel.accounting;


/**
* at/owlsoft/owl/corbamodel/accounting/ICorbaActivityOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public interface ICorbaActivityOperations 
{
  String getUUID ();
  long getStartDate ();
  at.owlsoft.owl.corbamodel.accounting.ICorbaActivityStatusEntry[] getActivityStatusEntries ();
  at.owlsoft.owl.corbamodel.media.ICorbaMediumExemplar getMediumExemplar ();
  at.owlsoft.owl.corbamodel.user.ICorbaSystemUser getCustomer ();
  at.owlsoft.owl.corbamodel.user.ICorbaSystemUser getCreator ();
  at.owlsoft.owl.corbamodel.media.ICorbaMedium getMedium ();
} // interface ICorbaActivityOperations
