package at.owlsoft.owl.corbamodel.accounting;


/**
* at/owlsoft/owl/corbamodel/accounting/ICorbaFilingExtensionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public interface ICorbaFilingExtensionOperations 
{
  long getCreationDate ();
  long getNewEndDate ();
  at.owlsoft.owl.corbamodel.accounting.ICorbaRental getRental ();
} // interface ICorbaFilingExtensionOperations
