package at.owlsoft.owl.corbamodel.accounting;


/**
* at/owlsoft/owl/corbamodel/accounting/ICorbaReservationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public interface ICorbaReservationOperations  extends at.owlsoft.owl.corbamodel.accounting.ICorbaActivityOperations
{
  int getDesiredDuration ();
} // interface ICorbaReservationOperations
