package at.owlsoft.owl.corbamodel.validation;


/**
* at/owlsoft/owl/corbamodel/validation/ICorbaValidationMessage.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public interface ICorbaValidationMessage extends ICorbaValidationMessageOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICorbaValidationMessage
