package at.owlsoft.owl.corbamodel.validation;


/**
* at/owlsoft/owl/corbamodel/validation/ICorbaValidationMessageOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public interface ICorbaValidationMessageOperations 
{
  at.owlsoft.owl.corbamodel.validation.CorbaValidationMessageStatus getStatus ();
  String getMessage ();
} // interface ICorbaValidationMessageOperations
