package at.owlsoft.owl.corbamodel.validation;


/**
* at/owlsoft/owl/corbamodel/validation/CorbaValidationMessageStatus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public class CorbaValidationMessageStatus implements org.omg.CORBA.portable.IDLEntity
{
  /**
     * 
     */
    private static final long serialVersionUID = -5874365005576865299L;
private        int __value;
  private static int __size = 2;
  private static at.owlsoft.owl.corbamodel.validation.CorbaValidationMessageStatus[] __array = new at.owlsoft.owl.corbamodel.validation.CorbaValidationMessageStatus [__size];

  public static final int _Warning = 0;
  public static final at.owlsoft.owl.corbamodel.validation.CorbaValidationMessageStatus Warning = new at.owlsoft.owl.corbamodel.validation.CorbaValidationMessageStatus(_Warning);
  public static final int _Error = 1;
  public static final at.owlsoft.owl.corbamodel.validation.CorbaValidationMessageStatus Error = new at.owlsoft.owl.corbamodel.validation.CorbaValidationMessageStatus(_Error);

  public int value ()
  {
    return __value;
  }

  public static at.owlsoft.owl.corbamodel.validation.CorbaValidationMessageStatus from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected CorbaValidationMessageStatus (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class CorbaValidationMessageStatus
