package at.owlsoft.owl.corbamodel.accounting;


/**
* at/owlsoft/owl/corbamodel/accounting/ICorbaActivityStatusEntryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public interface ICorbaActivityStatusEntryOperations 
{
  long getDate ();
  at.owlsoft.owl.corbamodel.accounting.ICorbaActivity getActivity ();
  at.owlsoft.owl.corbamodel.accounting.CorbaActivityStatus getActivityStatus ();
} // interface ICorbaActivityStatusEntryOperations
