package at.owlsoft.owl.corbamodel.accounting;


/**
* at/owlsoft/owl/corbamodel/accounting/ICorbaActivityPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public abstract class ICorbaActivityPOA extends org.omg.PortableServer.Servant
 implements at.owlsoft.owl.corbamodel.accounting.ICorbaActivityOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getUUID", new java.lang.Integer (0));
    _methods.put ("getStartDate", new java.lang.Integer (1));
    _methods.put ("getActivityStatusEntries", new java.lang.Integer (2));
    _methods.put ("getMediumExemplar", new java.lang.Integer (3));
    _methods.put ("getCustomer", new java.lang.Integer (4));
    _methods.put ("getCreator", new java.lang.Integer (5));
    _methods.put ("getMedium", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // at/owlsoft/owl/corbamodel/accounting/ICorbaActivity/getUUID
       {
         String $result = null;
         $result = this.getUUID ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // at/owlsoft/owl/corbamodel/accounting/ICorbaActivity/getStartDate
       {
         long $result = (long)0;
         $result = this.getStartDate ();
         out = $rh.createReply();
         out.write_longlong ($result);
         break;
       }

       case 2:  // at/owlsoft/owl/corbamodel/accounting/ICorbaActivity/getActivityStatusEntries
       {
         at.owlsoft.owl.corbamodel.accounting.ICorbaActivityStatusEntry $result[] = null;
         $result = this.getActivityStatusEntries ();
         out = $rh.createReply();
         at.owlsoft.owl.corbamodel.accounting._ActivityStatusEntryListHelper.write (out, $result);
         break;
       }

       case 3:  // at/owlsoft/owl/corbamodel/accounting/ICorbaActivity/getMediumExemplar
       {
         at.owlsoft.owl.corbamodel.media.ICorbaMediumExemplar $result = null;
         $result = this.getMediumExemplar ();
         out = $rh.createReply();
         at.owlsoft.owl.corbamodel.media.ICorbaMediumExemplarHelper.write (out, $result);
         break;
       }

       case 4:  // at/owlsoft/owl/corbamodel/accounting/ICorbaActivity/getCustomer
       {
         at.owlsoft.owl.corbamodel.user.ICorbaSystemUser $result = null;
         $result = this.getCustomer ();
         out = $rh.createReply();
         at.owlsoft.owl.corbamodel.user.ICorbaSystemUserHelper.write (out, $result);
         break;
       }

       case 5:  // at/owlsoft/owl/corbamodel/accounting/ICorbaActivity/getCreator
       {
         at.owlsoft.owl.corbamodel.user.ICorbaSystemUser $result = null;
         $result = this.getCreator ();
         out = $rh.createReply();
         at.owlsoft.owl.corbamodel.user.ICorbaSystemUserHelper.write (out, $result);
         break;
       }

       case 6:  // at/owlsoft/owl/corbamodel/accounting/ICorbaActivity/getMedium
       {
         at.owlsoft.owl.corbamodel.media.ICorbaMedium $result = null;
         $result = this.getMedium ();
         out = $rh.createReply();
         at.owlsoft.owl.corbamodel.media.ICorbaMediumHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:at/owlsoft/owl/corbamodel/accounting/ICorbaActivity:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ICorbaActivity _this() 
  {
    return ICorbaActivityHelper.narrow(
    super._this_object());
  }

  public ICorbaActivity _this(org.omg.CORBA.ORB orb) 
  {
    return ICorbaActivityHelper.narrow(
    super._this_object(orb));
  }


} // class ICorbaActivityPOA
