package at.owlsoft.owl.corbamodel.accounting;


/**
* at/owlsoft/owl/corbamodel/accounting/ICorbaReservation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public interface ICorbaReservation extends ICorbaReservationOperations, at.owlsoft.owl.corbamodel.accounting.ICorbaActivity, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICorbaReservation
