package at.owlsoft.owl.communication.corba;


/**
* at/owlsoft/owl/communication/corba/_ICorbaAuthenticationApiStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public class _ICorbaAuthenticationApiStub extends org.omg.CORBA.portable.ObjectImpl implements at.owlsoft.owl.communication.corba.ICorbaAuthenticationApi
{

  public at.owlsoft.owl.corbamodel.user.ICorbaSystemUser login (String userName, String password)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("login", true);
                $out.write_string (userName);
                $out.write_string (password);
                $in = _invoke ($out);
                at.owlsoft.owl.corbamodel.user.ICorbaSystemUser $result = at.owlsoft.owl.corbamodel.user.ICorbaSystemUserHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return login (userName, password        );
            } finally {
                _releaseReply ($in);
            }
  } // login

  public at.owlsoft.owl.corbamodel.user.ICorbaRole[] getRolesForCurrentUser ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getRolesForCurrentUser", true);
                $in = _invoke ($out);
                at.owlsoft.owl.corbamodel.user.ICorbaRole $result[] = at.owlsoft.owl.corbamodel.user._RoleListHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getRolesForCurrentUser (        );
            } finally {
                _releaseReply ($in);
            }
  } // getRolesForCurrentUser

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:at/owlsoft/owl/communication/corba/ICorbaAuthenticationApi:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ICorbaAuthenticationApiStub
