package at.owlsoft.owl.communication.corba;


/**
* at/owlsoft/owl/communication/corba/_ICorbaApiFactoryStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Mittwoch, 07. Dezember 2011 09:11 Uhr MEZ
*/

public class _ICorbaApiFactoryStub extends org.omg.CORBA.portable.ObjectImpl implements at.owlsoft.owl.communication.corba.ICorbaApiFactory
{

  public at.owlsoft.owl.communication.corba.ICorbaExtendApi createExtendApi ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createExtendApi", true);
                $in = _invoke ($out);
                at.owlsoft.owl.communication.corba.ICorbaExtendApi $result = at.owlsoft.owl.communication.corba.ICorbaExtendApiHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return createExtendApi (        );
            } finally {
                _releaseReply ($in);
            }
  } // createExtendApi

  public at.owlsoft.owl.communication.corba.ICorbaRentalApi createRentalApi ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createRentalApi", true);
                $in = _invoke ($out);
                at.owlsoft.owl.communication.corba.ICorbaRentalApi $result = at.owlsoft.owl.communication.corba.ICorbaRentalApiHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return createRentalApi (        );
            } finally {
                _releaseReply ($in);
            }
  } // createRentalApi

  public at.owlsoft.owl.communication.corba.ICorbaReservationApi createReservationApi ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createReservationApi", true);
                $in = _invoke ($out);
                at.owlsoft.owl.communication.corba.ICorbaReservationApi $result = at.owlsoft.owl.communication.corba.ICorbaReservationApiHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return createReservationApi (        );
            } finally {
                _releaseReply ($in);
            }
  } // createReservationApi

  public at.owlsoft.owl.communication.corba.ICorbaReturnApi createReturnApi ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createReturnApi", true);
                $in = _invoke ($out);
                at.owlsoft.owl.communication.corba.ICorbaReturnApi $result = at.owlsoft.owl.communication.corba.ICorbaReturnApiHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return createReturnApi (        );
            } finally {
                _releaseReply ($in);
            }
  } // createReturnApi

  public at.owlsoft.owl.communication.corba.ICorbaSystemUserApi createSystemUserApi ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createSystemUserApi", true);
                $in = _invoke ($out);
                at.owlsoft.owl.communication.corba.ICorbaSystemUserApi $result = at.owlsoft.owl.communication.corba.ICorbaSystemUserApiHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return createSystemUserApi (        );
            } finally {
                _releaseReply ($in);
            }
  } // createSystemUserApi

  public at.owlsoft.owl.communication.corba.ICorbaAuthenticationApi createAuthenticationApi ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createAuthenticationApi", true);
                $in = _invoke ($out);
                at.owlsoft.owl.communication.corba.ICorbaAuthenticationApi $result = at.owlsoft.owl.communication.corba.ICorbaAuthenticationApiHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return createAuthenticationApi (        );
            } finally {
                _releaseReply ($in);
            }
  } // createAuthenticationApi

  public at.owlsoft.owl.communication.corba.ICorbaSearchApi createSearchApi ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("createSearchApi", true);
                $in = _invoke ($out);
                at.owlsoft.owl.communication.corba.ICorbaSearchApi $result = at.owlsoft.owl.communication.corba.ICorbaSearchApiHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return createSearchApi (        );
            } finally {
                _releaseReply ($in);
            }
  } // createSearchApi

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:at/owlsoft/owl/communication/corba/ICorbaApiFactory:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ICorbaApiFactoryStub
