package at.owlsoft.owl.communication.corba;


/**
* at/owlsoft/owl/communication/corba/ICorbaApiFactory.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Mittwoch, 07. Dezember 2011 09:11 Uhr MEZ
*/

public interface ICorbaApiFactory extends ICorbaApiFactoryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICorbaApiFactory
