package at.owlsoft.owl.communication.corba;


/**
* at/owlsoft/owl/communication/corba/ICorbaSystemUserApiOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public interface ICorbaSystemUserApiOperations 
{
  at.owlsoft.owl.corbamodel.user.ICorbaSystemUser getSystemUserByCardID (int cardId);
} // interface ICorbaSystemUserApiOperations
