package at.owlsoft.owl.communication.corba;


/**
* at/owlsoft/owl/communication/corba/ICorbaApiFactoryPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public abstract class ICorbaApiFactoryPOA extends org.omg.PortableServer.Servant
 implements at.owlsoft.owl.communication.corba.ICorbaApiFactoryOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createExtendApi", new java.lang.Integer (0));
    _methods.put ("createRentalApi", new java.lang.Integer (1));
    _methods.put ("createReservationApi", new java.lang.Integer (2));
    _methods.put ("createReturnApi", new java.lang.Integer (3));
    _methods.put ("createSystemUserApi", new java.lang.Integer (4));
    _methods.put ("createAuthenticationApi", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // at/owlsoft/owl/communication/corba/ICorbaApiFactory/createExtendApi
       {
         at.owlsoft.owl.communication.corba.ICorbaExtendApi $result = null;
         $result = this.createExtendApi ();
         out = $rh.createReply();
         at.owlsoft.owl.communication.corba.ICorbaExtendApiHelper.write (out, $result);
         break;
       }

       case 1:  // at/owlsoft/owl/communication/corba/ICorbaApiFactory/createRentalApi
       {
         at.owlsoft.owl.communication.corba.ICorbaRentalApi $result = null;
         $result = this.createRentalApi ();
         out = $rh.createReply();
         at.owlsoft.owl.communication.corba.ICorbaRentalApiHelper.write (out, $result);
         break;
       }

       case 2:  // at/owlsoft/owl/communication/corba/ICorbaApiFactory/createReservationApi
       {
         at.owlsoft.owl.communication.corba.ICorbaReservationApi $result = null;
         $result = this.createReservationApi ();
         out = $rh.createReply();
         at.owlsoft.owl.communication.corba.ICorbaReservationApiHelper.write (out, $result);
         break;
       }

       case 3:  // at/owlsoft/owl/communication/corba/ICorbaApiFactory/createReturnApi
       {
         at.owlsoft.owl.communication.corba.ICorbaReturnApi $result = null;
         $result = this.createReturnApi ();
         out = $rh.createReply();
         at.owlsoft.owl.communication.corba.ICorbaReturnApiHelper.write (out, $result);
         break;
       }

       case 4:  // at/owlsoft/owl/communication/corba/ICorbaApiFactory/createSystemUserApi
       {
         at.owlsoft.owl.communication.corba.ICorbaSystemUserApi $result = null;
         $result = this.createSystemUserApi ();
         out = $rh.createReply();
         at.owlsoft.owl.communication.corba.ICorbaSystemUserApiHelper.write (out, $result);
         break;
       }

       case 5:  // at/owlsoft/owl/communication/corba/ICorbaApiFactory/createAuthenticationApi
       {
         at.owlsoft.owl.communication.corba.ICorbaAuthenticationApi $result = null;
         $result = this.createAuthenticationApi ();
         out = $rh.createReply();
         at.owlsoft.owl.communication.corba.ICorbaAuthenticationApiHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:at/owlsoft/owl/communication/corba/ICorbaApiFactory:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ICorbaApiFactory _this() 
  {
    return ICorbaApiFactoryHelper.narrow(
    super._this_object());
  }

  public ICorbaApiFactory _this(org.omg.CORBA.ORB orb) 
  {
    return ICorbaApiFactoryHelper.narrow(
    super._this_object(orb));
  }


} // class ICorbaApiFactoryPOA
