package at.owlsoft.owl.communication.corba;


/**
* at/owlsoft/owl/communication/corba/ICorbaRentalApiOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public interface ICorbaRentalApiOperations 
{
  at.owlsoft.owl.corbamodel.user.ICorbaSystemUser getRentalsForSystemUserCardId (int cardID);
  void newRental ();
  at.owlsoft.owl.corbamodel.user.ICorbaSystemUser setCustomer (int cardId);
  at.owlsoft.owl.corbamodel.media.ICorbaMediumExemplar setMediumExemplar (int exemplarId);
  at.owlsoft.owl.corbamodel.validation.ICorbaValidationMessage[] getValidationMessages ();
  void createNewExtension (String uuid);
  void returnRental (String uuid);
  at.owlsoft.owl.corbamodel.accounting.ICorbaRental getRental ();
  void setStartDate (long time);
  boolean store ();
} // interface ICorbaRentalApiOperations
