package at.owlsoft.owl.corbamodel;


/**
* at/owlsoft/owl/corbamodel/CorbaSearchFieldTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

abstract public class CorbaSearchFieldTypeHelper
{
  private static String  _id = "IDL:at/owlsoft/owl/corbamodel/CorbaSearchFieldType:1.0";

  public static void insert (org.omg.CORBA.Any a, at.owlsoft.owl.corbamodel.CorbaSearchFieldType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static at.owlsoft.owl.corbamodel.CorbaSearchFieldType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (at.owlsoft.owl.corbamodel.CorbaSearchFieldTypeHelper.id (), "CorbaSearchFieldType", new String[] { "Equals", "Greater", "Lesser"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static at.owlsoft.owl.corbamodel.CorbaSearchFieldType read (org.omg.CORBA.portable.InputStream istream)
  {
    return at.owlsoft.owl.corbamodel.CorbaSearchFieldType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, at.owlsoft.owl.corbamodel.CorbaSearchFieldType value)
  {
    ostream.write_long (value.value ());
  }

}
