package at.owlsoft.owl.corbamodel;


/**
* at/owlsoft/owl/corbamodel/CorbaSearchFieldType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public class CorbaSearchFieldType implements org.omg.CORBA.portable.IDLEntity
{
  /**
     * 
     */
    private static final long serialVersionUID = 8227119814595730027L;
private        int __value;
  private static int __size = 3;
  private static at.owlsoft.owl.corbamodel.CorbaSearchFieldType[] __array = new at.owlsoft.owl.corbamodel.CorbaSearchFieldType [__size];

  public static final int _Equals = 0;
  public static final at.owlsoft.owl.corbamodel.CorbaSearchFieldType Equals = new at.owlsoft.owl.corbamodel.CorbaSearchFieldType(_Equals);
  public static final int _Greater = 1;
  public static final at.owlsoft.owl.corbamodel.CorbaSearchFieldType Greater = new at.owlsoft.owl.corbamodel.CorbaSearchFieldType(_Greater);
  public static final int _Lesser = 2;
  public static final at.owlsoft.owl.corbamodel.CorbaSearchFieldType Lesser = new at.owlsoft.owl.corbamodel.CorbaSearchFieldType(_Lesser);

  public int value ()
  {
    return __value;
  }

  public static at.owlsoft.owl.corbamodel.CorbaSearchFieldType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected CorbaSearchFieldType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class CorbaSearchFieldType
