package at.owlsoft.owl.corbamodel;


/**
* at/owlsoft/owl/corbamodel/ICorbaSearchFieldCategoryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public interface ICorbaSearchFieldCategoryOperations 
{
  String getLabel ();
  at.owlsoft.owl.corbamodel.ISearchFieldDefinition[] getSearchFieldDefinitions ();
} // interface ICorbaSearchFieldCategoryOperations
