package at.owlsoft.owl.corbamodel;

/**
* at/owlsoft/owl/corbamodel/InvalidOperationExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public final class InvalidOperationExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public at.owlsoft.owl.corbamodel.InvalidOperationException value = null;

  public InvalidOperationExceptionHolder ()
  {
  }

  public InvalidOperationExceptionHolder (at.owlsoft.owl.corbamodel.InvalidOperationException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = at.owlsoft.owl.corbamodel.InvalidOperationExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    at.owlsoft.owl.corbamodel.InvalidOperationExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return at.owlsoft.owl.corbamodel.InvalidOperationExceptionHelper.type ();
  }

}
