package at.owlsoft.owl.corbamodel;


/**
* at/owlsoft/owl/corbamodel/InvalidOperationException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public final class InvalidOperationException extends org.omg.CORBA.UserException
{

  /**
     * 
     */
    private static final long serialVersionUID = 2252294211357887714L;


public InvalidOperationException ()
  {
    super(InvalidOperationExceptionHelper.id());
  } // ctor


  public InvalidOperationException (String $reason)
  {
    super(InvalidOperationExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class InvalidOperationException
