package at.owlsoft.owl.corbamodel;


/**
* at/owlsoft/owl/corbamodel/InvalidOperationExceptionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

abstract public class InvalidOperationExceptionHelper
{
  private static String  _id = "IDL:at/owlsoft/owl/corbamodel/InvalidOperationException:1.0";

  public static void insert (org.omg.CORBA.Any a, at.owlsoft.owl.corbamodel.InvalidOperationException that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static at.owlsoft.owl.corbamodel.InvalidOperationException extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [0];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          __typeCode = org.omg.CORBA.ORB.init ().create_exception_tc (at.owlsoft.owl.corbamodel.InvalidOperationExceptionHelper.id (), "InvalidOperationException", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static at.owlsoft.owl.corbamodel.InvalidOperationException read (org.omg.CORBA.portable.InputStream istream)
  {
    at.owlsoft.owl.corbamodel.InvalidOperationException value = new at.owlsoft.owl.corbamodel.InvalidOperationException ();
    // read and discard the repository ID
    istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, at.owlsoft.owl.corbamodel.InvalidOperationException value)
  {
    // write the repository ID
    ostream.write_string (id ());
  }

}
