package at.owlsoft.owl.corbamodel.media;


/**
* at/owlsoft/owl/corbamodel/media/_MediumListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public final class _MediumListHolder implements org.omg.CORBA.portable.Streamable
{
  public at.owlsoft.owl.corbamodel.media.ICorbaMedium value[] = null;

  public _MediumListHolder ()
  {
  }

  public _MediumListHolder (at.owlsoft.owl.corbamodel.media.ICorbaMedium[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = at.owlsoft.owl.corbamodel.media._MediumListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    at.owlsoft.owl.corbamodel.media._MediumListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return at.owlsoft.owl.corbamodel.media._MediumListHelper.type ();
  }

}
