package at.owlsoft.owl.corbamodel.media;

/**
* at/owlsoft/owl/corbamodel/media/CorbaMediumExemplarStatusHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public final class CorbaMediumExemplarStatusHolder implements org.omg.CORBA.portable.Streamable
{
  public at.owlsoft.owl.corbamodel.media.CorbaMediumExemplarStatus value = null;

  public CorbaMediumExemplarStatusHolder ()
  {
  }

  public CorbaMediumExemplarStatusHolder (at.owlsoft.owl.corbamodel.media.CorbaMediumExemplarStatus initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = at.owlsoft.owl.corbamodel.media.CorbaMediumExemplarStatusHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    at.owlsoft.owl.corbamodel.media.CorbaMediumExemplarStatusHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return at.owlsoft.owl.corbamodel.media.CorbaMediumExemplarStatusHelper.type ();
  }

}
