package at.owlsoft.owl.corbamodel.media;


/**
* at/owlsoft/owl/corbamodel/media/ICorbaMediumOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public interface ICorbaMediumOperations 
{
  int getMediumID ();
  String getPublisher ();
  String getName ();
  long getEntryDate ();
  long getPublishedDate ();
  at.owlsoft.owl.corbamodel.media.ITag[] getTags ();
  at.owlsoft.owl.corbamodel.media.ICorbaMediumExemplar[] getMediumExemplars ();
  at.owlsoft.owl.corbamodel.accounting.ICorbaActivity[] getActivities ();
} // interface ICorbaMediumOperations
