package at.owlsoft.owl.corbamodel.media;

/**
* at/owlsoft/owl/corbamodel/media/ICorbaMediumExemplarStatusEntryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public final class ICorbaMediumExemplarStatusEntryHolder implements org.omg.CORBA.portable.Streamable
{
  public at.owlsoft.owl.corbamodel.media.ICorbaMediumExemplarStatusEntry value = null;

  public ICorbaMediumExemplarStatusEntryHolder ()
  {
  }

  public ICorbaMediumExemplarStatusEntryHolder (at.owlsoft.owl.corbamodel.media.ICorbaMediumExemplarStatusEntry initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = at.owlsoft.owl.corbamodel.media.ICorbaMediumExemplarStatusEntryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    at.owlsoft.owl.corbamodel.media.ICorbaMediumExemplarStatusEntryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return at.owlsoft.owl.corbamodel.media.ICorbaMediumExemplarStatusEntryHelper.type ();
  }

}
