package at.owlsoft.owl.corbamodel.media;


/**
* at/owlsoft/owl/corbamodel/media/ICorbaMediumPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public abstract class ICorbaMediumPOA extends org.omg.PortableServer.Servant
 implements at.owlsoft.owl.corbamodel.media.ICorbaMediumOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getMediumID", new java.lang.Integer (0));
    _methods.put ("getPublisher", new java.lang.Integer (1));
    _methods.put ("getName", new java.lang.Integer (2));
    _methods.put ("getEntryDate", new java.lang.Integer (3));
    _methods.put ("getPublishedDate", new java.lang.Integer (4));
    _methods.put ("getTags", new java.lang.Integer (5));
    _methods.put ("getMediumExemplars", new java.lang.Integer (6));
    _methods.put ("getActivities", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // at/owlsoft/owl/corbamodel/media/ICorbaMedium/getMediumID
       {
         int $result = (int)0;
         $result = this.getMediumID ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // at/owlsoft/owl/corbamodel/media/ICorbaMedium/getPublisher
       {
         String $result = null;
         $result = this.getPublisher ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // at/owlsoft/owl/corbamodel/media/ICorbaMedium/getName
       {
         String $result = null;
         $result = this.getName ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // at/owlsoft/owl/corbamodel/media/ICorbaMedium/getEntryDate
       {
         long $result = (long)0;
         $result = this.getEntryDate ();
         out = $rh.createReply();
         out.write_longlong ($result);
         break;
       }

       case 4:  // at/owlsoft/owl/corbamodel/media/ICorbaMedium/getPublishedDate
       {
         long $result = (long)0;
         $result = this.getPublishedDate ();
         out = $rh.createReply();
         out.write_longlong ($result);
         break;
       }

       case 5:  // at/owlsoft/owl/corbamodel/media/ICorbaMedium/getTags
       {
         at.owlsoft.owl.corbamodel.media.ITag $result[] = null;
         $result = this.getTags ();
         out = $rh.createReply();
         at.owlsoft.owl.corbamodel.media._TagListHelper.write (out, $result);
         break;
       }

       case 6:  // at/owlsoft/owl/corbamodel/media/ICorbaMedium/getMediumExemplars
       {
         at.owlsoft.owl.corbamodel.media.ICorbaMediumExemplar $result[] = null;
         $result = this.getMediumExemplars ();
         out = $rh.createReply();
         at.owlsoft.owl.corbamodel.media._MediumExemplarListHelper.write (out, $result);
         break;
       }

       case 7:  // at/owlsoft/owl/corbamodel/media/ICorbaMedium/getActivities
       {
         at.owlsoft.owl.corbamodel.accounting.ICorbaActivity $result[] = null;
         $result = this.getActivities ();
         out = $rh.createReply();
         at.owlsoft.owl.corbamodel.accounting._ActivityListHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:at/owlsoft/owl/corbamodel/media/ICorbaMedium:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ICorbaMedium _this() 
  {
    return ICorbaMediumHelper.narrow(
    super._this_object());
  }

  public ICorbaMedium _this(org.omg.CORBA.ORB orb) 
  {
    return ICorbaMediumHelper.narrow(
    super._this_object(orb));
  }


} // class ICorbaMediumPOA
