package at.owlsoft.owl.corbamodel.media;


/**
* at/owlsoft/owl/corbamodel/media/TagType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public class TagType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 3;
  private static at.owlsoft.owl.corbamodel.media.TagType[] __array = new at.owlsoft.owl.corbamodel.media.TagType [__size];

  public static final int _Category = 0;
  public static final at.owlsoft.owl.corbamodel.media.TagType Category = new at.owlsoft.owl.corbamodel.media.TagType(_Category);
  public static final int _MediaMeta = 1;
  public static final at.owlsoft.owl.corbamodel.media.TagType MediaMeta = new at.owlsoft.owl.corbamodel.media.TagType(_MediaMeta);
  public static final int _AgeRestriction = 2;
  public static final at.owlsoft.owl.corbamodel.media.TagType AgeRestriction = new at.owlsoft.owl.corbamodel.media.TagType(_AgeRestriction);

  public int value ()
  {
    return __value;
  }

  public static at.owlsoft.owl.corbamodel.media.TagType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected TagType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class TagType
