package at.owlsoft.owl.communication.corba;


/**
* at/owlsoft/owl/communication/corba/_ApiFactoryListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public final class _ApiFactoryListHolder implements org.omg.CORBA.portable.Streamable
{
  public at.owlsoft.owl.communication.corba.ICorbaApiFactory value[] = null;

  public _ApiFactoryListHolder ()
  {
  }

  public _ApiFactoryListHolder (at.owlsoft.owl.communication.corba.ICorbaApiFactory[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = at.owlsoft.owl.communication.corba._ApiFactoryListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    at.owlsoft.owl.communication.corba._ApiFactoryListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return at.owlsoft.owl.communication.corba._ApiFactoryListHelper.type ();
  }

}
