package at.owlsoft.owl.communication.corba;


/**
* at/owlsoft/owl/communication/corba/_RentalApiListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public final class _RentalApiListHolder implements org.omg.CORBA.portable.Streamable
{
  public at.owlsoft.owl.communication.corba.ICorbaRentalApi value[] = null;

  public _RentalApiListHolder ()
  {
  }

  public _RentalApiListHolder (at.owlsoft.owl.communication.corba.ICorbaRentalApi[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = at.owlsoft.owl.communication.corba._RentalApiListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    at.owlsoft.owl.communication.corba._RentalApiListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return at.owlsoft.owl.communication.corba._RentalApiListHelper.type ();
  }

}
