package at.owlsoft.owl.communication.corba;


/**
* at/owlsoft/owl/communication/corba/ICorbaSearchApiOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public interface ICorbaSearchApiOperations 
{
  at.owlsoft.owl.corbamodel.ICorbaSearchFieldCategory[] getSearchFieldCategories ();
  at.owlsoft.owl.corbamodel.ICorbaSearchField addNewSearchField (String uniqueId);
  void removeSearchField (String uniqueId);
  void setSearchFieldData (String uniqueId, String key, String value);
  at.owlsoft.owl.corbamodel.media.ICorbaMedium[] search ();
} // interface ICorbaSearchApiOperations
