package at.owlsoft.owl.communication.corba;

/**
* at/owlsoft/owl/communication/corba/ICorbaReservationApiHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public final class ICorbaReservationApiHolder implements org.omg.CORBA.portable.Streamable
{
  public at.owlsoft.owl.communication.corba.ICorbaReservationApi value = null;

  public ICorbaReservationApiHolder ()
  {
  }

  public ICorbaReservationApiHolder (at.owlsoft.owl.communication.corba.ICorbaReservationApi initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = at.owlsoft.owl.communication.corba.ICorbaReservationApiHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    at.owlsoft.owl.communication.corba.ICorbaReservationApiHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return at.owlsoft.owl.communication.corba.ICorbaReservationApiHelper.type ();
  }

}
