package at.owlsoft.owl.communication.corba;


/**
* at/owlsoft/owl/communication/corba/ICorbaAuthenticationApiOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public interface ICorbaAuthenticationApiOperations 
{
  at.owlsoft.owl.corbamodel.user.ICorbaSystemUser login (String userName, String password);
  at.owlsoft.owl.corbamodel.user.ICorbaRole[] getRolesForCurrentUser ();
} // interface ICorbaAuthenticationApiOperations
