package at.owlsoft.owl.communication.corba;


/**
* at/owlsoft/owl/communication/corba/ICorbaSearchApiPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public abstract class ICorbaSearchApiPOA extends org.omg.PortableServer.Servant
 implements at.owlsoft.owl.communication.corba.ICorbaSearchApiOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getSearchFieldCategories", new java.lang.Integer (0));
    _methods.put ("addNewSearchField", new java.lang.Integer (1));
    _methods.put ("removeSearchField", new java.lang.Integer (2));
    _methods.put ("setSearchFieldData", new java.lang.Integer (3));
    _methods.put ("search", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // at/owlsoft/owl/communication/corba/ICorbaSearchApi/getSearchFieldCategories
       {
         at.owlsoft.owl.corbamodel.ICorbaSearchFieldCategory $result[] = null;
         $result = this.getSearchFieldCategories ();
         out = $rh.createReply();
         at.owlsoft.owl.corbamodel._SearchFieldCategoryListHelper.write (out, $result);
         break;
       }

       case 1:  // at/owlsoft/owl/communication/corba/ICorbaSearchApi/addNewSearchField
       {
         String uniqueId = in.read_string ();
         at.owlsoft.owl.corbamodel.ICorbaSearchField $result = null;
         $result = this.addNewSearchField (uniqueId);
         out = $rh.createReply();
         at.owlsoft.owl.corbamodel.ICorbaSearchFieldHelper.write (out, $result);
         break;
       }

       case 2:  // at/owlsoft/owl/communication/corba/ICorbaSearchApi/removeSearchField
       {
         String uniqueId = in.read_string ();
         this.removeSearchField (uniqueId);
         out = $rh.createReply();
         break;
       }

       case 3:  // at/owlsoft/owl/communication/corba/ICorbaSearchApi/setSearchFieldData
       {
         String uniqueId = in.read_string ();
         String key = in.read_string ();
         String value = in.read_string ();
         this.setSearchFieldData (uniqueId, key, value);
         out = $rh.createReply();
         break;
       }

       case 4:  // at/owlsoft/owl/communication/corba/ICorbaSearchApi/search
       {
         at.owlsoft.owl.corbamodel.media.ICorbaMedium $result[] = null;
         $result = this.search ();
         out = $rh.createReply();
         at.owlsoft.owl.corbamodel.media._MediumListHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:at/owlsoft/owl/communication/corba/ICorbaSearchApi:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ICorbaSearchApi _this() 
  {
    return ICorbaSearchApiHelper.narrow(
    super._this_object());
  }

  public ICorbaSearchApi _this(org.omg.CORBA.ORB orb) 
  {
    return ICorbaSearchApiHelper.narrow(
    super._this_object(orb));
  }


} // class ICorbaSearchApiPOA
