package at.owlsoft.owl.communication.corba;


/**
* at/owlsoft/owl/communication/corba/ICorbaRentalApiPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public abstract class ICorbaRentalApiPOA extends org.omg.PortableServer.Servant
 implements at.owlsoft.owl.communication.corba.ICorbaRentalApiOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getRentalsForSystemUserCardId", new java.lang.Integer (0));
    _methods.put ("newRental", new java.lang.Integer (1));
    _methods.put ("setCustomer", new java.lang.Integer (2));
    _methods.put ("setMediumExemplar", new java.lang.Integer (3));
    _methods.put ("getValidationMessages", new java.lang.Integer (4));
    _methods.put ("createNewExtension", new java.lang.Integer (5));
    _methods.put ("returnRental", new java.lang.Integer (6));
    _methods.put ("getRental", new java.lang.Integer (7));
    _methods.put ("setStartDate", new java.lang.Integer (8));
    _methods.put ("store", new java.lang.Integer (9));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // at/owlsoft/owl/communication/corba/ICorbaRentalApi/getRentalsForSystemUserCardId
       {
         int cardID = in.read_long ();
         at.owlsoft.owl.corbamodel.user.ICorbaSystemUser $result = null;
         $result = this.getRentalsForSystemUserCardId (cardID);
         out = $rh.createReply();
         at.owlsoft.owl.corbamodel.user.ICorbaSystemUserHelper.write (out, $result);
         break;
       }

       case 1:  // at/owlsoft/owl/communication/corba/ICorbaRentalApi/newRental
       {
         this.newRental ();
         out = $rh.createReply();
         break;
       }

       case 2:  // at/owlsoft/owl/communication/corba/ICorbaRentalApi/setCustomer
       {
         int cardId = in.read_long ();
         at.owlsoft.owl.corbamodel.user.ICorbaSystemUser $result = null;
         $result = this.setCustomer (cardId);
         out = $rh.createReply();
         at.owlsoft.owl.corbamodel.user.ICorbaSystemUserHelper.write (out, $result);
         break;
       }

       case 3:  // at/owlsoft/owl/communication/corba/ICorbaRentalApi/setMediumExemplar
       {
         int exemplarId = in.read_long ();
         at.owlsoft.owl.corbamodel.media.ICorbaMediumExemplar $result = null;
         $result = this.setMediumExemplar (exemplarId);
         out = $rh.createReply();
         at.owlsoft.owl.corbamodel.media.ICorbaMediumExemplarHelper.write (out, $result);
         break;
       }

       case 4:  // at/owlsoft/owl/communication/corba/ICorbaRentalApi/getValidationMessages
       {
         at.owlsoft.owl.corbamodel.validation.ICorbaValidationMessage $result[] = null;
         $result = this.getValidationMessages ();
         out = $rh.createReply();
         at.owlsoft.owl.corbamodel.validation._ValidationMessageListHelper.write (out, $result);
         break;
       }

       case 5:  // at/owlsoft/owl/communication/corba/ICorbaRentalApi/createNewExtension
       {
         String uuid = in.read_string ();
         this.createNewExtension (uuid);
         out = $rh.createReply();
         break;
       }

       case 6:  // at/owlsoft/owl/communication/corba/ICorbaRentalApi/returnRental
       {
         String uuid = in.read_string ();
         this.returnRental (uuid);
         out = $rh.createReply();
         break;
       }

       case 7:  // at/owlsoft/owl/communication/corba/ICorbaRentalApi/getRental
       {
         at.owlsoft.owl.corbamodel.accounting.ICorbaRental $result = null;
         $result = this.getRental ();
         out = $rh.createReply();
         at.owlsoft.owl.corbamodel.accounting.ICorbaRentalHelper.write (out, $result);
         break;
       }

       case 8:  // at/owlsoft/owl/communication/corba/ICorbaRentalApi/setStartDate
       {
         long time = in.read_longlong ();
         this.setStartDate (time);
         out = $rh.createReply();
         break;
       }

       case 9:  // at/owlsoft/owl/communication/corba/ICorbaRentalApi/store
       {
         boolean $result = false;
         $result = this.store ();
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:at/owlsoft/owl/communication/corba/ICorbaRentalApi:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ICorbaRentalApi _this() 
  {
    return ICorbaRentalApiHelper.narrow(
    super._this_object());
  }

  public ICorbaRentalApi _this(org.omg.CORBA.ORB orb) 
  {
    return ICorbaRentalApiHelper.narrow(
    super._this_object(orb));
  }


} // class ICorbaRentalApiPOA
