package at.owlsoft.owl.corbamodel.media.ICorbaMediumExemplarPackage;


/**
* at/owlsoft/owl/corbamodel/media/ICorbaMediumExemplarPackage/_metaDataKeysHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public final class _metaDataKeysHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public _metaDataKeysHolder ()
  {
  }

  public _metaDataKeysHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = at.owlsoft.owl.corbamodel.media.ICorbaMediumExemplarPackage._metaDataKeysHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    at.owlsoft.owl.corbamodel.media.ICorbaMediumExemplarPackage._metaDataKeysHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return at.owlsoft.owl.corbamodel.media.ICorbaMediumExemplarPackage._metaDataKeysHelper.type ();
  }

}
