package at.owlsoft.owl.corbamodel.ICorbaSearchFieldCategoryPackage;

/**
 * at/owlsoft/owl/corbamodel/ICorbaSearchFieldCategoryPackage/
 * _SearchFieldDefinitionListHolder.java . Generated by the IDL-to-Java compiler
 * (portable), version "3.2" from corbamodel.idl Montag, 05. Dezember 2011 12:57
 * Uhr MEZ
 */

public final class _SearchFieldDefinitionListHolder implements
        org.omg.CORBA.portable.Streamable
{
    public at.owlsoft.owl.corbamodel.ISearchFieldDefinition value[] = null;

    public _SearchFieldDefinitionListHolder()
    {
    }

    public _SearchFieldDefinitionListHolder(
            at.owlsoft.owl.corbamodel.ISearchFieldDefinition[] initialValue)
    {
        value = initialValue;
    }

    @Override
    public void _read(org.omg.CORBA.portable.InputStream i)
    {
        value = at.owlsoft.owl.corbamodel.ICorbaSearchFieldCategoryPackage._SearchFieldDefinitionListHelper
                .read(i);
    }

    @Override
    public void _write(org.omg.CORBA.portable.OutputStream o)
    {
        at.owlsoft.owl.corbamodel.ICorbaSearchFieldCategoryPackage._SearchFieldDefinitionListHelper
                .write(o, value);
    }

    @Override
    public org.omg.CORBA.TypeCode _type()
    {
        return at.owlsoft.owl.corbamodel.ICorbaSearchFieldCategoryPackage._SearchFieldDefinitionListHelper
                .type();
    }

}
