package at.owlsoft.owl.corbamodel.media;


/**
* at/owlsoft/owl/corbamodel/media/CorbaMediumExemplarStatus.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public class CorbaMediumExemplarStatus implements org.omg.CORBA.portable.IDLEntity
{
  /**
     * 
     */
    private static final long serialVersionUID = 5788676382043039249L;
private        int __value;
  private static int __size = 4;
  private static at.owlsoft.owl.corbamodel.media.CorbaMediumExemplarStatus[] __array = new at.owlsoft.owl.corbamodel.media.CorbaMediumExemplarStatus [__size];

  public static final int _Rentable = 0;
  public static final at.owlsoft.owl.corbamodel.media.CorbaMediumExemplarStatus Rentable = new at.owlsoft.owl.corbamodel.media.CorbaMediumExemplarStatus(_Rentable);
  public static final int _Rented = 1;
  public static final at.owlsoft.owl.corbamodel.media.CorbaMediumExemplarStatus Rented = new at.owlsoft.owl.corbamodel.media.CorbaMediumExemplarStatus(_Rented);
  public static final int _Returned = 2;
  public static final at.owlsoft.owl.corbamodel.media.CorbaMediumExemplarStatus Returned = new at.owlsoft.owl.corbamodel.media.CorbaMediumExemplarStatus(_Returned);
  public static final int _StockItem = 3;
  public static final at.owlsoft.owl.corbamodel.media.CorbaMediumExemplarStatus StockItem = new at.owlsoft.owl.corbamodel.media.CorbaMediumExemplarStatus(_StockItem);

  public int value ()
  {
    return __value;
  }

  public static at.owlsoft.owl.corbamodel.media.CorbaMediumExemplarStatus from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected CorbaMediumExemplarStatus (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class CorbaMediumExemplarStatus
