package at.owlsoft.owl.corbamodel.media;


/**
* at/owlsoft/owl/corbamodel/media/ICorbaMediumExemplarStatusEntryOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public interface ICorbaMediumExemplarStatusEntryOperations 
{
  long getDate ();
  at.owlsoft.owl.corbamodel.media.ICorbaMediumExemplar getMediumExemplar ();
  at.owlsoft.owl.corbamodel.media.CorbaMediumExemplarStatus getMediumExemplarStatus ();
} // interface ICorbaMediumExemplarStatusEntryOperations
