package at.owlsoft.owl.corbamodel.media;


/**
* at/owlsoft/owl/corbamodel/media/ICorbaMediumExemplarPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public abstract class ICorbaMediumExemplarPOA extends org.omg.PortableServer.Servant
 implements at.owlsoft.owl.corbamodel.media.ICorbaMediumExemplarOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("getExemplarID", new java.lang.Integer (0));
    _methods.put ("getMetaData", new java.lang.Integer (1));
    _methods.put ("getMetaDataKeys", new java.lang.Integer (2));
    _methods.put ("getMedium", new java.lang.Integer (3));
    _methods.put ("getMediumExemplarStatusEntries", new java.lang.Integer (4));
    _methods.put ("getActivities", new java.lang.Integer (5));
    _methods.put ("getLastRental", new java.lang.Integer (6));
    _methods.put ("getCurrentState", new java.lang.Integer (7));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // at/owlsoft/owl/corbamodel/media/ICorbaMediumExemplar/getExemplarID
       {
         int $result = (int)0;
         $result = this.getExemplarID ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // at/owlsoft/owl/corbamodel/media/ICorbaMediumExemplar/getMetaData
       {
         String key = in.read_string ();
         String $result = null;
         $result = this.getMetaData (key);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // at/owlsoft/owl/corbamodel/media/ICorbaMediumExemplar/getMetaDataKeys
       {
         String $result[] = null;
         $result = this.getMetaDataKeys ();
         out = $rh.createReply();
         at.owlsoft.owl.corbamodel.media.ICorbaMediumExemplarPackage._metaDataKeysHelper.write (out, $result);
         break;
       }

       case 3:  // at/owlsoft/owl/corbamodel/media/ICorbaMediumExemplar/getMedium
       {
         at.owlsoft.owl.corbamodel.media.ICorbaMedium $result = null;
         $result = this.getMedium ();
         out = $rh.createReply();
         at.owlsoft.owl.corbamodel.media.ICorbaMediumHelper.write (out, $result);
         break;
       }

       case 4:  // at/owlsoft/owl/corbamodel/media/ICorbaMediumExemplar/getMediumExemplarStatusEntries
       {
         at.owlsoft.owl.corbamodel.media.ICorbaMediumExemplarStatusEntry $result[] = null;
         $result = this.getMediumExemplarStatusEntries ();
         out = $rh.createReply();
         at.owlsoft.owl.corbamodel.media._MediumExemplarStatusEntryListHelper.write (out, $result);
         break;
       }

       case 5:  // at/owlsoft/owl/corbamodel/media/ICorbaMediumExemplar/getActivities
       {
         at.owlsoft.owl.corbamodel.accounting.ICorbaActivity $result[] = null;
         $result = this.getActivities ();
         out = $rh.createReply();
         at.owlsoft.owl.corbamodel.accounting._ActivityListHelper.write (out, $result);
         break;
       }

       case 6:  // at/owlsoft/owl/corbamodel/media/ICorbaMediumExemplar/getLastRental
       {
         at.owlsoft.owl.corbamodel.accounting.ICorbaRental $result = null;
         $result = this.getLastRental ();
         out = $rh.createReply();
         at.owlsoft.owl.corbamodel.accounting.ICorbaRentalHelper.write (out, $result);
         break;
       }

       case 7:  // at/owlsoft/owl/corbamodel/media/ICorbaMediumExemplar/getCurrentState
       {
         at.owlsoft.owl.corbamodel.media.CorbaMediumExemplarStatus $result = null;
         $result = this.getCurrentState ();
         out = $rh.createReply();
         at.owlsoft.owl.corbamodel.media.CorbaMediumExemplarStatusHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:at/owlsoft/owl/corbamodel/media/ICorbaMediumExemplar:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ICorbaMediumExemplar _this() 
  {
    return ICorbaMediumExemplarHelper.narrow(
    super._this_object());
  }

  public ICorbaMediumExemplar _this(org.omg.CORBA.ORB orb) 
  {
    return ICorbaMediumExemplarHelper.narrow(
    super._this_object(orb));
  }


} // class ICorbaMediumExemplarPOA
