package at.owlsoft.owl.corbamodel.media;

/**
* at/owlsoft/owl/corbamodel/media/TagTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from corbamodel.idl
* Montag, 05. Dezember 2011 12:57 Uhr MEZ
*/

public final class TagTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public at.owlsoft.owl.corbamodel.media.TagType value = null;

  public TagTypeHolder ()
  {
  }

  public TagTypeHolder (at.owlsoft.owl.corbamodel.media.TagType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = at.owlsoft.owl.corbamodel.media.TagTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    at.owlsoft.owl.corbamodel.media.TagTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return at.owlsoft.owl.corbamodel.media.TagTypeHelper.type ();
  }

}
